-- Mac app DAU bucket (task b4591534).
--
-- Purely additive, with a default, so no existing row is rewritten and no
-- existing query changes meaning. A deployment that never sees a Mac request
-- carries a column of zeros.
--
-- The traffic already exists: the iOS/Mac client has sent `x-platform: mac-app`
-- on every request since build 232, and detectPlatform read x-platform before
-- any user-agent sniffing — but there was no Mac member of AnalyticsPlatform,
-- so it landed in UNKNOWN. This column is where it goes from now on.
--
-- NOT BACKFILLED, deliberately: past days' Mac traffic is inside dauUnknown and
-- cannot be separated after the fact — the daily rows store counts, not the
-- requests they were derived from. Mac numbers start from this deploy.
-- CORRECTED 2026-08-16: this said "DailyStats". There is no such table — the
-- model is AnalyticsDailyStats and carries no @@map, so the deploy failed with
-- 42P01 and, because a failed migration blocks the ones behind it, took the
-- unrelated User.taskDisplayMode migration down with it. Production had already
-- moved past this record by the time it was fixed, so the column is actually
-- added by 20260816130000_analytics_mac_app_dau_fix; this line is what makes a
-- FRESH database correct, and the IF NOT EXISTS is what keeps the two from
-- colliding.
ALTER TABLE "AnalyticsDailyStats" ADD COLUMN IF NOT EXISTS "dauMacApp" INTEGER NOT NULL DEFAULT 0;
