/**
 * Parity proof for markdown (AWTD-1064): the browser's renderer held to astrid-core's.
 *
 * Descriptions, comments and chat render in the browser only (lib/markdown.ts
 * `renderMarkdownWithLinks`, `marked` + DOMPurify), and the browser cannot load the WebAssembly
 * core without loosening the Content Security Policy, which this does not do. So the web keeps
 * its TypeScript renderer, and this pins it to the core's `renderMarkdown`, which is what the iOS
 * and Mac apps draw. Every case of the markdown fixture (generated by running this repo's
 * renderer in a jsdom window, scripts/contract-fixtures/drivers/markdown.mjs, and vendored at the
 * pinned core revision) is:
 *
 * - rendered here, now, and read back into blocks (scripts/contract-fixtures/markdown-blocks.mjs).
 *   It must equal the fixture, so the fixture is today's renderer;
 * - rendered by the vendored core (`renderMarkdown`, with the reader's identifier context when the
 *   case has one). It must equal the same blocks, so web and iOS draw the same thing;
 * - and the HTML itself is checked against the sanitiser's contract: only allowlisted tags and
 *   attributes, no script, handler, frame or style, and no address other than http, https, mailto
 *   or a relative address on this site. That includes the `xss-*` cases.
 *
 * D38 (the ordered list's start, references inside code, typed HTML) was resolved toward iOS: the
 * fixture has no disputed cases.
 */
import { readFileSync } from 'node:fs'
import path from 'node:path'
import { describe, expect, it } from 'vitest'
import { renderMarkdownWithLinks } from '@/lib/markdown'
import { loadCoreRulesFrom } from '@/lib/core-rules/wasm'
import { blocksOfHtml } from '../../scripts/contract-fixtures/markdown-blocks.mjs'

const PACKAGE_DIR = path.join(process.cwd(), 'packages', 'astrid-rules')

interface Case {
  id: string
  text: string
  context: { projectKey?: string; keys: string[]; hidden?: string[] } | null
  html: string
  blocks: unknown[]
}
interface Fixture {
  cases: Case[]
  disputed: Case[]
  disputes: unknown[]
}

const read = (file: string) => JSON.parse(readFileSync(file, 'utf8')) as Fixture
const fixture = read(path.join(PACKAGE_DIR, 'fixtures', 'markdown.json'))
const core = loadCoreRulesFrom(PACKAGE_DIR)
const cases = fixture.cases.map((c) => [c.id, c] as const)

function coreBlocks(c: Case): unknown {
  const reply = JSON.parse(
    core.runJson(JSON.stringify({ kind: 'renderMarkdown', text: c.text, ...(c.context ? { identifiers: c.context } : {}) })),
  ) as { ok: boolean; value: unknown }
  expect(reply.ok).toBe(true)
  return reply.value
}

const render = (c: Case) => renderMarkdownWithLinks(c.text, c.context ? { identifiers: c.context } : undefined)

// The sanitiser's contract (lib/markdown.ts RICH_TEXT_TAGS / RICH_TEXT_ATTRS), restated here so a
// change to the allowlist has to change this too.
const TAGS = new Set(['P', 'BR', 'SPAN', 'STRONG', 'EM', 'DEL', 'CODE', 'PRE', 'H1', 'H2', 'H3', 'H4', 'H5', 'H6', 'UL', 'OL', 'LI', 'BLOCKQUOTE', 'HR', 'TABLE', 'THEAD', 'TBODY', 'TR', 'TH', 'TD', 'A', 'INPUT'])
const ATTRS = new Set(['href', 'target', 'rel', 'class', 'type', 'checked', 'disabled', 'align', 'start'])
// http, https, mailto, or relative to the app (no scheme, not protocol-relative). `[](u1)` is a
// relative link to "u1", as it always was. It stays on this site.
const SAFE_HREF = /^(https?:\/\/|mailto:|(?![a-z][a-z0-9+.-]*:)(?!\/\/))/i

function sanitisationProblems(html: string): string[] {
  const problems: string[] = []
  const body = document.createElement('body')
  body.innerHTML = html
  for (const el of Array.from(body.querySelectorAll('*'))) {
    if (!TAGS.has(el.tagName)) problems.push(`tag ${el.tagName}`)
    for (const attr of Array.from(el.attributes)) {
      if (!ATTRS.has(attr.name)) problems.push(`attribute ${attr.name} on ${el.tagName}`)
    }
    const href = el.getAttribute('href')
    if (href !== null && !SAFE_HREF.test(href)) problems.push(`href ${href}`)
    if (el.tagName === 'INPUT' && (el.getAttribute('type') !== 'checkbox' || !el.hasAttribute('disabled'))) {
      problems.push('an input that is not a disabled checkbox')
    }
    if (el.tagName === 'A' && /^https?:/i.test(el.getAttribute('href') ?? '') && el.getAttribute('rel') !== 'noopener noreferrer') {
      problems.push('an outbound link without rel=noopener noreferrer')
    }
  }
  if (/javascript:|vbscript:|data:text\/html/i.test(html.replace(/>[^<]*</g, '><'))) problems.push('a dangerous scheme in markup')
  return problems
}

describe('the markdown fixture at the pinned core revision', () => {
  it('is the one this repo exports, and has no disputed cases left', () => {
    // contracts/fixtures/markdown.json is checked against the renderer by check:contract-fixtures.
    const ours = read(path.join(process.cwd(), 'contracts', 'fixtures', 'markdown.json'))
    expect(fixture.cases).toEqual(ours.cases)
    expect(fixture.disputed).toEqual([])
    expect(fixture.disputes).toEqual([])
    expect(fixture.cases.length).toBeGreaterThanOrEqual(130)
    expect(fixture.cases.filter((c) => c.id.startsWith('xss-')).length).toBeGreaterThanOrEqual(20)
  })
})

describe('the browser renderer draws what the fixture records', () => {
  it.each(cases)('%s', (_id, c) => {
    expect(blocksOfHtml(document, render(c))).toEqual(c.blocks)
  })
})

describe('astrid-core draws the same blocks (what iOS and the Mac show)', () => {
  it.each(cases)('%s', (_id, c) => {
    expect(coreBlocks(c)).toEqual(c.blocks)
  })
})

describe('the HTML keeps to the sanitiser’s contract', () => {
  it.each(cases)('%s', (_id, c) => {
    expect(sanitisationProblems(render(c))).toEqual([])
  })
})
