// @vitest-environment node
/**
 * Parity proof for lib/task-manager-utils.ts `parseTaskInput` against astrid-core's `smartParse`
 * (AWTD-1062).
 *
 * parseTaskInput runs only in the browser (hooks/useTaskManagerController.ts, the quick-add box),
 * which cannot load the vendored WebAssembly, so on the web it is still the TypeScript that
 * parses — nothing is routed through the core. What this pins is that the two parsers agree, so
 * a line typed on the web and the same line typed on iOS or the Mac (which parse through the
 * core) make the same task. Both are run over every case of the smart fixture — generated by
 * running this repo's parseTaskInput under a pinned clock — and the comparison is the one
 * astrid-core's own smart_contract.rs makes, for the two documented differences
 * (astrid-core docs/CONTRACTS.md):
 *
 * - D12: a date word is a calendar day in the core and an instant here, so the day is compared.
 * - The core answers the `#tags`; the selected list is appended by its create command. So the
 *   core's lists are a prefix of web's, short by at most the selected list.
 *
 * (D13, "assign to" / "for", is left out of the fixture by its driver.)
 */
import { readFileSync } from 'node:fs'
import path from 'node:path'
import { afterAll, beforeAll, describe, expect, it, vi } from 'vitest'
import { parseTaskInput } from '@/lib/task-manager-utils'
import type { TaskList } from '@/types/task'
import { loadCoreRulesFrom } from '@/lib/core-rules/wasm'

const PACKAGE_DIR = path.join(process.cwd(), 'packages', 'astrid-rules')

interface Fixture {
  now: string
  lists: Array<{ id: string; name: string; isVirtual: boolean }>
  keywords: unknown
  cases: Array<{
    locale: string
    input: string
    selectedListId: string
    title: string
    listIds: string[]
    dueDate: string | null
    priority: number | null
    repeating: string | null
    weekdays: string[]
  }>
}

const read = (file: string) => JSON.parse(readFileSync(file, 'utf8')) as Fixture
const fixture = read(path.join(PACKAGE_DIR, 'fixtures', 'smart.json'))
const core = loadCoreRulesFrom(PACKAGE_DIR)
const cases = fixture.cases.map((c) => [`[${c.locale}] ${JSON.stringify(c.input)}`, c] as const)

describe('the smart fixture at the pinned core revision', () => {
  it('is the one this repo exports — so the TypeScript, the fixture and the core are one chain', () => {
    // contracts/fixtures/smart.json is checked against the TypeScript by check:contract-fixtures.
    const ours = read(path.join(process.cwd(), 'contracts', 'fixtures', 'smart.json'))
    expect(fixture.now).toBe(ours.now)
    expect(fixture.lists).toEqual(ours.lists)
    expect(fixture.keywords).toEqual(ours.keywords)
    expect(fixture.cases).toEqual(ours.cases)
    expect(fixture.cases.length).toBeGreaterThanOrEqual(200)
  })
})

describe('the TypeScript parser (the browser) under the fixture clock', () => {
  beforeAll(() => {
    vi.useFakeTimers({ now: new Date(fixture.now), toFake: ['Date'] })
  })
  afterAll(() => {
    vi.useRealTimers()
  })

  it.each(cases)('%s', (_name, c) => {
    const parsed = parseTaskInput(c.input, c.selectedListId, undefined, fixture.lists as TaskList[], false, c.locale)
    expect({
      title: parsed.title,
      listIds: parsed.listIds,
      dueDay: parsed.dueDateTime ? new Date(parsed.dueDateTime).toISOString().slice(0, 10) : null,
      priority: parsed.priority ?? null,
      repeating: parsed.repeating ?? null,
      weekdays: parsed.customRepeatingData?.weekdays ?? [],
    }).toEqual({
      title: c.title,
      listIds: c.listIds,
      dueDay: c.dueDate?.slice(0, 10) ?? null,
      priority: c.priority,
      repeating: c.repeating,
      weekdays: c.weekdays,
    })
  })
})

describe("astrid-core's smartParse, as iOS and the Mac call it", () => {
  const today = fixture.now.slice(0, 10)

  it.each(cases)('%s', (_name, c) => {
    const reply = JSON.parse(
      core.runJson(JSON.stringify({ kind: 'smartParse', text: c.input, lists: fixture.lists, locale: c.locale, today })),
    ) as { ok: boolean; value: { title: string; listIds: string[]; dueDay: string | null; priority: number | null; repeating: string | null; weekdays: string[] } }

    expect(reply.ok).toBe(true)
    const v = reply.value
    expect(v.title).toBe(c.title)
    expect(c.listIds.slice(0, v.listIds.length)).toEqual(v.listIds)
    expect(c.listIds.length - v.listIds.length).toBeLessThanOrEqual(1)
    expect(v.dueDay ?? null).toBe(c.dueDate?.slice(0, 10) ?? null)
    expect(v.priority ?? null).toBe(c.priority)
    expect(v.repeating ?? null).toBe(c.repeating)
    expect(v.weekdays ?? []).toEqual(c.weekdays)
  })
})
