// @vitest-environment node
/**
 * Parity proof for lib/search-query-parser.ts parsed by astrid-core (AWTD-1062).
 *
 * The search fixture is generated by running this repo's own parser (astrid-core
 * contracts/export-from-web.mjs; scripts/export-contract-fixtures.ts writes the same cases into
 * contracts/fixtures/ here) and vendored at the pinned core revision. Every query goes through
 * parseSearchQuery twice: with the TypeScript parsing (the fallback) and with the vendored
 * WebAssembly core installed as the server installs it. Both must give the fixture's parse, and
 * the core must have answered every query itself. The search grammar has no disputed cases
 * (docs/CONTRACTS.md in astrid-core): the core follows web exactly.
 */
import { readFileSync } from 'node:fs'
import path from 'node:path'
import { afterEach, describe, expect, it } from 'vitest'
import { isEmptySearch, parseSearchQuery, priorityToNumber, setSearchQueryCore } from '@/lib/search-query-parser'
import { createSearchQueryCore } from '@/lib/core-rules/search-query-core'
import { loadCoreRulesFrom } from '@/lib/core-rules/wasm'

const PACKAGE_DIR = path.join(process.cwd(), 'packages', 'astrid-rules')

interface Fixture {
  priorityNumbers: Record<string, number>
  queries: Array<{ query: string; parsed: ReturnType<typeof parseSearchQuery>; isEmpty: boolean }>
}

const read = (file: string) => JSON.parse(readFileSync(file, 'utf8')) as Fixture & Record<string, unknown>
const fixture = read(path.join(PACKAGE_DIR, 'fixtures', 'search.json'))
const core = loadCoreRulesFrom(PACKAGE_DIR)
const cases = fixture.queries.map((c) => [JSON.stringify(c.query), c] as const)

afterEach(() => setSearchQueryCore(null))

describe('the search fixture at the pinned core revision', () => {
  it('is the one this repo exports — so the TypeScript, the fixture and the core are one chain', () => {
    // contracts/fixtures/search.json is checked against the TypeScript by check:contract-fixtures.
    const ours = read(path.join(process.cwd(), 'contracts', 'fixtures', 'search.json'))
    expect(fixture.queries).toEqual(ours.queries)
    expect(fixture.priorityNumbers).toEqual(ours.priorityNumbers)
    expect(fixture.queries.length).toBeGreaterThanOrEqual(30)
  })
})

describe('the TypeScript parser alone (the fallback)', () => {
  it.each(cases)('%s', (_name, { query, parsed, isEmpty }) => {
    const answer = parseSearchQuery(query)
    expect(answer).toEqual(parsed)
    expect(isEmptySearch(answer)).toBe(isEmpty)
  })

  it('numbers priorities as the fixture does', () => {
    for (const [word, number] of Object.entries(fixture.priorityNumbers)) {
      expect(priorityToNumber(word as Parameters<typeof priorityToNumber>[0])).toBe(number)
    }
  })
})

describe('parseSearchQuery with astrid-core parsing, as the server runs it', () => {
  it.each(cases)('%s', (_name, { query, parsed, isEmpty }) => {
    const reports: unknown[] = []
    const parser = createSearchQueryCore(core.runJson, {
      disagreement: (d) => reports.push(d),
      failure: (d) => reports.push(d),
    })
    setSearchQueryCore(parser.parse)

    const answer = parseSearchQuery(query)
    expect(answer).toEqual(parsed)
    expect(isEmptySearch(answer)).toBe(isEmpty)
    // The core answered itself — no fallback — and agreed.
    expect(reports).toEqual([])
    expect(parser.stats).toEqual({ agreed: 1, disagreed: 0, skipped: 0, failed: 0 })
  })
})
