// @vitest-environment node
/**
 * Parity proof for repeating-task rollover decided by astrid-core (AWTD-1063).
 *
 * The repeating fixture is generated by running this repo's own calculator (types/repeating.ts,
 * scripts/contract-fixtures/drivers/repeating.mjs) and vendored at the pinned core revision. Its
 * `completions` and `zonedProgressions` are whole `nextOccurrence` requests, with the person's
 * zone, exactly as the server's completion path sends them. Every one goes through
 * nextOccurrenceForTask twice: with the TypeScript answering (the fallback) and with the vendored
 * WebAssembly core installed as the server installs it. Both must give the fixture's answer, and the
 * core must have answered every request itself.
 *
 * Web follows the core on D1, D3 and D4 (astrid-core docs/CONTRACTS.md, resolved toward iOS
 * 2026-10-03), so the fixture has no disputed cases. A seeded sweep of random requests across
 * zones with daylight saving checks the two agree beyond the named cases too.
 */
import { readFileSync } from 'node:fs'
import path from 'node:path'
import { afterEach, describe, expect, it } from 'vitest'
import { nextOccurrenceForTask, setRepeatingCore } from '@/lib/repeating-rollover'
import { createRepeatingCore } from '@/lib/core-rules/repeating-core'
import { loadCoreRulesFrom } from '@/lib/core-rules/wasm'
import { calculateTaskNextOccurrence, type TaskNextOccurrence, type TaskNextOccurrenceInput } from '@/types/repeating'

const PACKAGE_DIR = path.join(process.cwd(), 'packages', 'astrid-rules')

interface Fixture {
  simple: unknown[]
  simpleEndConditions: unknown[]
  custom: unknown[]
  customProgressions: unknown[]
  completions: Array<{ name: string; request: TaskNextOccurrenceInput; answer: TaskNextOccurrence }>
  zonedProgressions: Array<{
    name: string
    repeating: string
    pattern: unknown
    start: string
    timeZone: string
    isAllDay: boolean
    steps: number
    dates: string[]
  }>
}

const read = (file: string) => JSON.parse(readFileSync(file, 'utf8')) as Fixture
const fixture = read(path.join(PACKAGE_DIR, 'fixtures', 'repeating.json'))
const core = loadCoreRulesFrom(PACKAGE_DIR)
const completions = fixture.completions.map((c) => [c.name, c] as const)
const progressions = fixture.zonedProgressions.map((c) => [c.name, c] as const)

/** Instants compared as instants: the core writes no milliseconds. */
const same = (answer: TaskNextOccurrence) => ({
  ...answer,
  nextDueDate: answer.nextDueDate === null ? null : new Date(answer.nextDueDate).getTime(),
})

function withCore() {
  const reports: unknown[] = []
  const hook = createRepeatingCore(core.runJson, {
    disagreement: (d) => reports.push(d),
    failure: (d) => reports.push(d),
  })
  setRepeatingCore(hook.next)
  return { hook, reports }
}

afterEach(() => setRepeatingCore(null))

describe('the repeating fixture at the pinned core revision', () => {
  it('is the one this repo exports — so the TypeScript, the fixture and the core are one chain', () => {
    // contracts/fixtures/repeating.json is checked against the TypeScript by check:contract-fixtures.
    const ours = read(path.join(process.cwd(), 'contracts', 'fixtures', 'repeating.json'))
    for (const section of ['simple', 'simpleEndConditions', 'custom', 'customProgressions', 'completions', 'zonedProgressions'] as const) {
      expect(fixture[section]).toEqual(ours[section])
    }
    expect(fixture.completions.length).toBeGreaterThanOrEqual(40)
  })
})

describe('the TypeScript alone (the fallback)', () => {
  it.each(completions)('%s', (_name, { request, answer }) => {
    expect(same(nextOccurrenceForTask(request))).toEqual(same(answer))
  })
})

describe('nextOccurrenceForTask with astrid-core answering, as the server runs it', () => {
  it.each(completions)('%s', (_name, { request, answer }) => {
    const { hook, reports } = withCore()
    expect(same(nextOccurrenceForTask(request))).toEqual(same(answer))
    // The core answered itself — no fallback — and agreed.
    expect(reports).toEqual([])
    expect(hook.stats).toEqual({ agreed: 1, disagreed: 0, skipped: 0, failed: 0 })
  })

  it.each(progressions)('%s, step by step', (_name, c) => {
    const { hook, reports } = withCore()
    const dates: number[] = []
    let current = c.start
    let occurrenceCount = 0
    for (let i = 0; i < c.steps; i++) {
      const answer = nextOccurrenceForTask({
        repeating: c.repeating,
        pattern: c.pattern,
        currentDueDate: current,
        completion: current,
        repeatFrom: 'DUE_DATE',
        occurrenceCount,
        timeZone: c.timeZone,
        isAllDay: c.isAllDay,
      })
      if (!answer.nextDueDate) break
      dates.push(new Date(answer.nextDueDate).getTime())
      current = answer.nextDueDate
      occurrenceCount = answer.newOccurrenceCount
    }
    expect(dates).toEqual(c.dates.map((d) => new Date(d).getTime()))
    expect(reports).toEqual([])
    expect(hook.stats.agreed).toBe(c.steps)
  })
})

describe('beyond the named cases', () => {
  it('agrees with the core on a seeded sweep of random requests across zones', () => {
    const zones = ['UTC', 'America/Los_Angeles', 'Europe/Paris', 'Asia/Tokyo', 'Australia/Lord_Howe', 'America/Sao_Paulo', 'Asia/Kolkata', 'Pacific/Chatham', 'America/St_Johns']
    const weekdays = ['sunday', 'monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday']
    let seed = 1063
    const random = () => (seed = (seed * 1103515245 + 12345) % 2147483648) / 2147483648
    const pick = <T,>(values: T[]) => values[Math.floor(random() * values.length)]

    const disagreements: unknown[] = []
    for (let i = 0; i < 2000; i++) {
      const base = Date.UTC(2025, 0, 1) + Math.floor(random() * 3 * 365 * 86_400) * 1000
      const isAllDay = random() < 0.3
      const due = random() < 0.1 ? null : isAllDay ? Math.floor(base / 86_400_000) * 86_400_000 : Math.floor(base / 60_000) * 60_000
      const end = pick<Record<string, unknown>>([
        { endCondition: 'never' },
        { endCondition: 'after_occurrences', endAfterOccurrences: Math.floor(random() * 5) },
        { endCondition: 'until_date', endUntilDate: new Date(base + Math.floor(random() * 60 * 86_400_000)).toISOString() },
      ])
      const repeating = pick(['daily', 'weekly', 'monthly', 'yearly', 'custom', 'custom', 'custom'])
      let pattern: Record<string, unknown> | null = random() < 0.5 ? end : null
      if (repeating === 'custom') {
        const unit = pick(['days', 'weeks', 'months', 'years'])
        pattern = { type: 'custom', unit, interval: 1 + Math.floor(random() * 3), ...end }
        if (unit === 'weeks') pattern.weekdays = weekdays.filter(() => random() < 0.35)
        if (unit === 'months') {
          pattern.monthRepeatType = pick(['same_date', 'same_weekday'])
          pattern.monthWeekday = { weekday: pick(weekdays), weekOfMonth: 1 + Math.floor(random() * 5) }
        }
        if (unit === 'years') Object.assign(pattern, { month: 1 + Math.floor(random() * 12), day: 1 + Math.floor(random() * 31) })
      }
      const request: TaskNextOccurrenceInput = {
        repeating,
        pattern,
        currentDueDate: due === null ? null : new Date(due).toISOString(),
        completion: new Date(base + Math.floor((random() - 0.3) * 10 * 86_400_000)).toISOString(),
        repeatFrom: pick(['DUE_DATE', 'COMPLETION_DATE'] as const),
        occurrenceCount: Math.floor(random() * 4),
        timeZone: pick(zones),
        isAllDay,
      }
      const typescript = calculateTaskNextOccurrence(request)
      const { hook } = withCore()
      const answer = nextOccurrenceForTask(request)
      if (hook.stats.agreed !== 1 || JSON.stringify(same(answer)) !== JSON.stringify(same(typescript))) {
        disagreements.push({ request, typescript, answer, stats: hook.stats })
      }
    }
    expect(disagreements).toEqual([])
  })
})
