/**
 * AWTD-1031: the cross-platform contract fixtures are exported by THIS repo.
 *
 * The JSON astrid-core's Rust tests compile in — shortcuts, repeating, permissions, board,
 * statuses, editing, search, smart, task identifiers — is generated from astrid-web's sources.
 * The generator used to live in the consumer (astrid-core `contracts/export-from-web.mjs`), so a
 * change here that moved a shared rule only surfaced as a red build in another repo, after the
 * fact. Owning the export here means `--check` fails in the PR that made the change.
 *
 * What this pins:
 *  - the exporter exists, and its `--check` passes against the checked-in fixtures;
 *  - it writes every fixture astrid-core reads, by name;
 *  - predeploy runs the check, so drift is caught before it is merged.
 */

import { describe, it, expect } from 'vitest'
import { spawnSync } from 'node:child_process'
import { existsSync, readFileSync } from 'node:fs'
import { join } from 'node:path'
import { getChecks } from '../../scripts/predeploy-self-healing'

const repoRoot = join(__dirname, '..', '..')
const fixturesDir = join(repoRoot, 'contracts', 'fixtures')

// The names astrid-core's tests read. Renaming one breaks the Rust side, so it is pinned here.
const FIXTURES = [
  'shortcuts.json',
  'repeating.json',
  'permissions.json',
  'board.json',
  'statuses.json',
  'editing.json',
  'search.json',
  'smart.json',
  'task-identifiers.json',
]

describe('AWTD-1031: contract fixtures are exported from astrid-web', () => {
  it('checks in every fixture astrid-core reads, marked as generated', () => {
    for (const name of FIXTURES) {
      const path = join(fixturesDir, name)
      expect(existsSync(path), `contracts/fixtures/${name}`).toBe(true)
      const fixture = JSON.parse(readFileSync(path, 'utf8'))
      expect(fixture.$comment).toMatch(/GENERATED by scripts\/export-contract-fixtures\.ts/)
    }
  })

  it(
    'regenerates byte-identical fixtures from the current sources (--check)',
    () => {
      const run = spawnSync(
        process.execPath,
        ['--import', 'tsx', join(repoRoot, 'scripts', 'export-contract-fixtures.ts'), '--check'],
        { cwd: repoRoot, encoding: 'utf8' },
      )
      expect(run.stderr).toBe('')
      expect(run.status).toBe(0)
      for (const name of FIXTURES) expect(run.stdout).toContain(`ok  contracts/fixtures/${name}`)
    },
    120_000,
  )

  it('is a predeploy gate, so drift fails where the shared rule was changed', () => {
    const check = getChecks().find((c) => c.command === 'npm run check:contract-fixtures')
    expect(check).toBeDefined()
    expect(check?.autoFixable).toBe(false)

    const pkg = JSON.parse(readFileSync(join(repoRoot, 'package.json'), 'utf8'))
    expect(pkg.scripts['check:contract-fixtures']).toBe('tsx scripts/export-contract-fixtures.ts --check')
    expect(pkg.scripts['export:contract-fixtures']).toBe('tsx scripts/export-contract-fixtures.ts')
  })
})
